"""init

Revision ID: 2f85c899757a
Revises: 
Create Date: 2024-09-12 22:08:20.285054

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f85c899757a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_bids",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "version_tenders",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bids",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Canceled", native_enum=False),
            nullable=True,
        ),
        sa.Column("tenderId", sa.Uuid(), nullable=False),
        sa.Column("authorId", sa.Uuid(), nullable=False),
        sa.Column(
            "authorType",
            sa.Enum("Organization", "User", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("decision_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorId"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["version_bids.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenderId"],
            ["version_tenders.id"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "feedback",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("tenderId", sa.Uuid(), nullable=False),
        sa.Column("bidFeedback", sa.String(), nullable=False),
        sa.Column("creatorUsername", sa.String(length=50), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("authorId", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creatorUsername"],
            ["employee.username"],
        ),
        sa.ForeignKeyConstraint(
            ["authorId"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenderId"],
            ["version_tenders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tenders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "serviceType",
            sa.Enum("Construction", "Delivery", "Manufacture", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("Created", "Published", "Closed", native_enum=False),
            nullable=True,
        ),
        sa.Column("organizationId", sa.Uuid(), nullable=False),
        sa.Column("creatorId", sa.Uuid(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["creatorId"],
            ["employee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["version_tenders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organizationId"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenders")
    op.drop_table("feedback")
    op.drop_table("bids")
    op.drop_table("version_tenders")
    op.drop_table("version_bids")
    # ### end Alembic commands ###
